# Generated by Django 4.0.5 on 2022-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('weather_main', models.CharField(max_length=50)),
                ('weather_desscription', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
            ],
        ),
    ]
